# Generated by Django 6.0 on 2025-12-27 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=200)),
                ('Location', models.CharField(max_length=100)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bed_room', models.IntegerField(max_length=10)),
                ('bath', models.IntegerField(max_length=10)),
                ('square_ft', models.IntegerField(max_length=10)),
            ],
        ),
    ]
