# Generated by Django 6.0 on 2025-12-27 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='Type',
            field=models.CharField(default='Bungalow', max_length=100),
        ),
        migrations.AddField(
            model_name='house',
            name='bathroom',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='house',
            name='bedroom',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='house',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='house',
            name='kitchen',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='house',
            name='sale',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='house',
            name='sitting_room',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='house',
            name='bath',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='house',
            name='bed_room',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='house',
            name='square_ft',
            field=models.IntegerField(),
        ),
    ]
