# Generated by Django 6.0 on 2026-01-12 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0002_house_type_house_bathroom_house_bedroom_house_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter_Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=200)),
            ],
        ),
    ]
