# Generated by Django 6.0 on 2026-01-13 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0003_newsletter_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter_email',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
