# Generated by Django 6.0 on 2026-01-17 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0005_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='Type',
        ),
        migrations.AddField(
            model_name='house',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='houses.category'),
        ),
    ]
